### ISSUE TITLE
Downgrades the Gurobi version 

### ISSUE THREAD

**Issue by akulbansal5** [martinbiel/StochasticPrograms.jl#46] opened 2023-01-13 05:11 UTC
Installing the package StochasticPrograms.jl downgrades Gurobi v0.11.5 to Gurobi v0.11.3. This results in "Failed to precompile Gurobi" error while importing the Gurobi package. I am using Gurobi version 9.1.2 on my mac.

**Comment by odow** [comment] 2023-08-22 20:22
See https://github.com/martinbiel/StochasticPrograms.jl/issues/49

**Comment by odow** [comment] 2024-01-07 23:26
Closing as duplicate of #49

**Closed as completed by odow** 2024-01-07 23:26 UTC
